<div class="topBanner">
	<div class="logo">
	<a href="http://www.nationalarchives.gov.uk"><img src="/images/micrositea.gif" width="44" height="30" title="The National Archives" alt="The National Archives" align="middle" border="0" /></a>
	<a href="/default.htm"><img src="/images/sm_learningcurvelogo.gif" alt="Learning Curve" width="121" height="31" border="0" title="Learning Curve" align="middle"/></a>
	</div>
	<div class="topLink">
		<div class="hide"><a href="#skipnav" accesskey="s" title="skip navigation">skip navigation</a></div>
		<div><a href="http://www.nationalarchives.gov.uk" title="The National Archives homepage" class="topmenu">The National Archives homepage<img src="/images/arrows/arrowright.gif" alt="" title="red arrow" width="11" height="11" class="toplink" /></a></div>
		<div><a href="http://www.nationalarchives.gov.uk/teachers" title="More resources for teachers" class="topmenu">More resources for teachers<img src="/images/arrows/arrowright.gif" alt="" title="red arrow" width="11" height="11" class="toplink" /></a></div>
	</div>
</div>